name: Deploy
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Set Environment Variables
      run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env.local
        echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> .env.local
        echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env.local
        echo "NEXT_PUBLIC_BYTESCALE_API_KEY=${{ secrets.NEXT_PUBLIC_BYTESCALE_API_KEY }}" >> .env.local
      shell: bash

    - name: Run Migrations
      run: npm run migrate

    - name: Build Application
      run: npm run build

    - name: Restart PM2 Server Process
      run: pm2 restart 2ht-app --silent
